# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/matt/code/deck_runner

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/matt/code/deck_runner

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/matt/code/deck_runner/CMakeFiles /home/matt/code/deck_runner//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/matt/code/deck_runner/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named client

# Build rule for target.
client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 client
.PHONY : client

# fast build rule for target.
client/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/build
.PHONY : client/fast

src/assets/assets.o: src/assets/assets.cpp.o
.PHONY : src/assets/assets.o

# target to build an object file
src/assets/assets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/assets/assets.cpp.o
.PHONY : src/assets/assets.cpp.o

src/assets/assets.i: src/assets/assets.cpp.i
.PHONY : src/assets/assets.i

# target to preprocess a source file
src/assets/assets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/assets/assets.cpp.i
.PHONY : src/assets/assets.cpp.i

src/assets/assets.s: src/assets/assets.cpp.s
.PHONY : src/assets/assets.s

# target to generate assembly for a file
src/assets/assets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/assets/assets.cpp.s
.PHONY : src/assets/assets.cpp.s

src/camera.o: src/camera.cpp.o
.PHONY : src/camera.o

# target to build an object file
src/camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/camera.cpp.o
.PHONY : src/camera.cpp.o

src/camera.i: src/camera.cpp.i
.PHONY : src/camera.i

# target to preprocess a source file
src/camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/camera.cpp.i
.PHONY : src/camera.cpp.i

src/camera.s: src/camera.cpp.s
.PHONY : src/camera.s

# target to generate assembly for a file
src/camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/camera.cpp.s
.PHONY : src/camera.cpp.s

src/platform/platform_sdl.o: src/platform/platform_sdl.cpp.o
.PHONY : src/platform/platform_sdl.o

# target to build an object file
src/platform/platform_sdl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/platform/platform_sdl.cpp.o
.PHONY : src/platform/platform_sdl.cpp.o

src/platform/platform_sdl.i: src/platform/platform_sdl.cpp.i
.PHONY : src/platform/platform_sdl.i

# target to preprocess a source file
src/platform/platform_sdl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/platform/platform_sdl.cpp.i
.PHONY : src/platform/platform_sdl.cpp.i

src/platform/platform_sdl.s: src/platform/platform_sdl.cpp.s
.PHONY : src/platform/platform_sdl.s

# target to generate assembly for a file
src/platform/platform_sdl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/platform/platform_sdl.cpp.s
.PHONY : src/platform/platform_sdl.cpp.s

src/platform/renderer.o: src/platform/renderer.cpp.o
.PHONY : src/platform/renderer.o

# target to build an object file
src/platform/renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/platform/renderer.cpp.o
.PHONY : src/platform/renderer.cpp.o

src/platform/renderer.i: src/platform/renderer.cpp.i
.PHONY : src/platform/renderer.i

# target to preprocess a source file
src/platform/renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/platform/renderer.cpp.i
.PHONY : src/platform/renderer.cpp.i

src/platform/renderer.s: src/platform/renderer.cpp.s
.PHONY : src/platform/renderer.s

# target to generate assembly for a file
src/platform/renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/platform/renderer.cpp.s
.PHONY : src/platform/renderer.cpp.s

src/render/mesh.o: src/render/mesh.cpp.o
.PHONY : src/render/mesh.o

# target to build an object file
src/render/mesh.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/render/mesh.cpp.o
.PHONY : src/render/mesh.cpp.o

src/render/mesh.i: src/render/mesh.cpp.i
.PHONY : src/render/mesh.i

# target to preprocess a source file
src/render/mesh.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/render/mesh.cpp.i
.PHONY : src/render/mesh.cpp.i

src/render/mesh.s: src/render/mesh.cpp.s
.PHONY : src/render/mesh.s

# target to generate assembly for a file
src/render/mesh.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/render/mesh.cpp.s
.PHONY : src/render/mesh.cpp.s

src/render/ui.o: src/render/ui.cpp.o
.PHONY : src/render/ui.o

# target to build an object file
src/render/ui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/render/ui.cpp.o
.PHONY : src/render/ui.cpp.o

src/render/ui.i: src/render/ui.cpp.i
.PHONY : src/render/ui.i

# target to preprocess a source file
src/render/ui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/render/ui.cpp.i
.PHONY : src/render/ui.cpp.i

src/render/ui.s: src/render/ui.cpp.s
.PHONY : src/render/ui.s

# target to generate assembly for a file
src/render/ui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/render/ui.cpp.s
.PHONY : src/render/ui.cpp.s

src/sMath.o: src/sMath.cpp.o
.PHONY : src/sMath.o

# target to build an object file
src/sMath.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/sMath.cpp.o
.PHONY : src/sMath.cpp.o

src/sMath.i: src/sMath.cpp.i
.PHONY : src/sMath.i

# target to preprocess a source file
src/sMath.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/sMath.cpp.i
.PHONY : src/sMath.cpp.i

src/sMath.s: src/sMath.cpp.s
.PHONY : src/sMath.s

# target to generate assembly for a file
src/sMath.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/sMath.cpp.s
.PHONY : src/sMath.cpp.s

src/shared.o: src/shared.cpp.o
.PHONY : src/shared.o

# target to build an object file
src/shared.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared.cpp.o
.PHONY : src/shared.cpp.o

src/shared.i: src/shared.cpp.i
.PHONY : src/shared.i

# target to preprocess a source file
src/shared.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared.cpp.i
.PHONY : src/shared.cpp.i

src/shared.s: src/shared.cpp.s
.PHONY : src/shared.s

# target to generate assembly for a file
src/shared.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared.cpp.s
.PHONY : src/shared.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... client"
	@echo "... src/assets/assets.o"
	@echo "... src/assets/assets.i"
	@echo "... src/assets/assets.s"
	@echo "... src/camera.o"
	@echo "... src/camera.i"
	@echo "... src/camera.s"
	@echo "... src/platform/platform_sdl.o"
	@echo "... src/platform/platform_sdl.i"
	@echo "... src/platform/platform_sdl.s"
	@echo "... src/platform/renderer.o"
	@echo "... src/platform/renderer.i"
	@echo "... src/platform/renderer.s"
	@echo "... src/render/mesh.o"
	@echo "... src/render/mesh.i"
	@echo "... src/render/mesh.s"
	@echo "... src/render/ui.o"
	@echo "... src/render/ui.i"
	@echo "... src/render/ui.s"
	@echo "... src/sMath.o"
	@echo "... src/sMath.i"
	@echo "... src/sMath.s"
	@echo "... src/shared.o"
	@echo "... src/shared.i"
	@echo "... src/shared.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

